name: Update Index

on:
  push:
    branches: [ main ]
    paths:
      - '**.tgz'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Helm Installation
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0
      - name: Update Index
        run: |
          helm repo index .
          git config --global user.email "autodev.oct@gmail.com"
          git config --global user.name "octubre-bot"
          git add index.yaml
          git commit -m "Update chart index"
          git push
